#version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile

    image: replicator

    depends_on:
#      - replicator_zookeeper_1
#      - replicator_zookeeper_2
      replicator_kafka_1:
        condition: service_healthy
      replicator_kafka_2:
        condition: service_healthy
      replicator_prometheus:
        condition: service_started
      replicator_grafana:
        condition: service_started
      replicator_observer:
        condition: service_started

    volumes:
#      - ./:/app/
      - ./examples/:/app/examples
      - ssl-certs:/ssl-certs

    environment:
      RUST_LOG: debug

    command: cargo run --offline --frozen --bin=kafka-replicator -- -h 0.0.0.0 examples/templates.yml

    ports:
      - 9444:9444

    networks:
      replicator_rust_env_network:
        aliases:
          - replicator-app.test


  replicator_observer:
    image: replicator

    depends_on:
      replicator_kafka_1:
        condition: service_healthy
      replicator_kafka_2:
        condition: service_healthy
      replicator_prometheus:
        condition: service_started
      replicator_grafana:
        condition: service_started

    volumes:
      - ./examples/:/app/examples
      - ssl-certs:/ssl-certs

    environment:
      RUST_LOG: debug

    command: cargo run --offline --frozen --bin=kafka-observer -- examples/templates.yml -h 0.0.0.0 -p 9445

    ports:
      - 9445:9445

    networks:
      replicator_rust_env_network:
        aliases:
          - replicator-observer.test


#  replicator_zookeeper_1:
#    image: wurstmeister/zookeeper
#
#    ports:
#      - 2181:2181
#    networks:
#      replicator_rust_env_network:
#        aliases:
#          - replicator-zookeeper-1.test

#  replicator_zookeeper_2:
#    image: wurstmeister/zookeeper
#
#    ports:
#      - 2182:2181
#    networks:
#      replicator_rust_env_network:
#        aliases:
#          - replicator-zookeeper-2.test

#  replicator_kafka_1:
#    image: wurstmeister/kafka:2.11-1.1.0
#
#    depends_on:
#      - replicator_zookeeper_1
#
#    ports:
#      - 9092:9092
#
#    environment:
#      #KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
#      KAFKA_CREATE_TOPICS: "topic1:3:1,topic2:3:1,topic3:3:1"
#      KAFKA_ZOOKEEPER_CONNECT: replicator-zookeeper-1.test:2181
#      # BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2}'"
#      KAFKA_BROKER_ID: 1
#
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#
#    networks:
#      replicator_rust_env_network:
#        aliases:
#          - replicator-kafka-1.test

  replicator_kafka_1:
      image: kafka-ssl-local:latest

      ports:
        - 9093:9093
        - 9094:9094
        - 2281:2181

      init: true

      environment:
        DOMAIN: "replicator-kafka-1.test"
        SSL_PORT: 9093
        PLAINTEXT_PORT: 9094
        BROKER_ID: 101

      volumes:
        - ssl-certs:/ssl-certs

      networks:
        replicator_rust_env_network:
          aliases:
            - replicator-kafka-1.test

#  replicator_kafka_2:
#    image: wurstmeister/kafka:2.11-1.1.0
#
#    depends_on:
#      - replicator_zookeeper_2
#
#    ports:
#      - 9192:9092
#
#    environment:
#      #KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
#      KAFKA_CREATE_TOPICS: "topic1:3:1,topic2:3:1,topic3:3:1"
#      KAFKA_ZOOKEEPER_CONNECT: replicator-zookeeper-2.test:2181
#      # BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2}'"
#      KAFKA_BROKER_ID: 2
#
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#
#    networks:
#      replicator_rust_env_network:
#        aliases:
#          - replicator-kafka-2.test

  replicator_kafka_2:
    image: kafka-ssl-local:latest

    ports:
      - 9193:9193
      - 9194:9194
      - 2381:2181

    init: true

    environment:
      DOMAIN: "replicator-kafka-2.test"
      SSL_PORT: 9193
      PLAINTEXT_PORT: 9194
      BROKER_ID: 102

    volumes:
      - ssl-certs:/ssl-certs

    networks:
      replicator_rust_env_network:
        aliases:
          - replicator-kafka-2.test

  replicator_kafkacat:
    image: edenhill/kafkacat:1.5.0

    volumes:
      - ./:/app/

    environment:
      KAFKA_HOST: replicator-kafka-1.test

    entrypoint: /bin/sh


    networks:
      replicator_rust_env_network:
        aliases:
          - replicator-kafkacat-1.test

  replicator_grafana:
    image: grafana/grafana:local

    ports:
      - 3000:3000

    networks:
      replicator_rust_env_network:
        aliases:
          - replicator-grafana-1.test

  replicator_prometheus:
    image: prom/prometheus:latest

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - 9090:9090

    networks:
      replicator_rust_env_network:
        aliases:
          - replicator-prometheus-1.test

networks:
  replicator_rust_env_network:

volumes:
  ssl-certs: