{
 "title": "Kafka Replicator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number Of Records",
   "type": "stat",
   "gridPos": { "h": 33, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service:kafka_observer:number_of_records{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Transfered Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "rate(service:kafka_replicator:transfered_total_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining For Topic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "service:kafka_observer:remaining_for_topic",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "rate(service:kafka_replicator:total_bytes[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}